export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const ADD_TOURNAMENTS = "ADD_TOURNAMENTS";
export const FETCH_TOURNAMENTS = "FETCH_TOURNAMENTS";

export const ADD_PLAYERS = "ADD_PLAYERS";
export const FETCH_PLAYERS = "FETCH_PLAYERS";
